const app=document.querySelector('#app');
const breadcrumb=document.querySelector('#breadcrumb');
const qs=new URLSearchParams(location.search);const type=qs.get('type');const id=qs.get('id');let published=new Set();
const dirs={plan:'plans',concrete_plan:'concrete-plans',route:'routes',spot:'spots'};
const pathFor=(t,i)=>`./data/${dirs[t]}/${i}.json`;const hrefFor=r=>`./?type=${encodeURIComponent(r.type)}&id=${encodeURIComponent(r.id)}`;const keyFor=r=>`${r.type}:${r.id}`;const canOpen=r=>r?.type&&r?.id&&published.has(keyFor(r));
const esc=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const labels={mode:{train:'電車',air:'飛行機',rental_car:'レンタカー',rental_car_and_mountain_access:'車＋登山アクセス',walk:'徒歩',bus:'バス',drive:'車',car:'車'},difficulty:{easy:'やさしい',easy_to_medium:'やさしい〜中程度',medium:'中程度',medium_to_hard:'中程度〜難しい',hard:'難しい'},role:{main:'主役',core:'主役',support:'補助',optional:'任意',fallback:'代替',start:'開始',end:'終了',parking:'駐車',access:'アクセス',transfer:'乗換・移動',lodging:'宿泊',primary:'主役'},status:{draft:'作成中',ready:'実施可能',completed:'完了',cancelled:'中止',viable:'実施可能',conditional:'条件付き',unknown:'未確認'}};
const human=(g,v='')=>v?(labels[g]?.[v]||String(v).replaceAll('_',' ')):'';const modeLabel=v=>human('mode',v);const roleLabel=v=>human('role',v);const difficultyLabel=v=>human('difficulty',v);const statusLabel=v=>human('status',v);
async function fetchJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json();}
function refInline(ref){if(!ref)return'';const label=esc(ref.label||ref.id||'');return canOpen(ref)?`<a href="${hrefFor(ref)}">${label}</a>`:label;}
function refCard(ref){return `<article class="card ref-card"><div>${refInline(ref)}</div>${ref.role?`<span class="badge">${esc(roleLabel(ref.role))}</span>`:''}</article>`;}
function endpoint(ref){if(!ref)return'';return ref.type==='travel_point'?esc(ref.label||ref.id||''):refInline(ref);}
function badge(text){return text?`<span class="badge">${esc(text)}</span>`:'';}
function routeStops(refs=[]){return refs.length?`<div class="route-stops">${refs.map((x,i)=>`<span class="route-stop"><span class="stop-no">${i+1}</span>${refInline(x)}${x.role?` <small>${esc(roleLabel(x.role))}</small>`:''}</span>`).join('<span class="route-arrow">→</span>')}</div>`:'';}
function flowItem(item,execution=false){
  if(item.type==='transfer'){
    const schedule=item.schedule||{};const time=schedule.depart_at||schedule.arrive_at||'';const service=item.transport_service||{};const meta=[item.duration_estimate,item.duration,schedule.depart_at&&schedule.arrive_at?`${schedule.depart_at} → ${schedule.arrive_at}`:'',service.service_name||service.operator].filter(Boolean).join(' · ');
    return `<li class="flow-item transfer"><div class="flow-icon">↔</div><div>${time?`<div class="exec-flow-time">${esc(time)}</div>`:''}<div class="flow-title">移動 ${badge(modeLabel(item.mode))}</div>${meta?`<div class="flow-detail">${esc(meta)}</div>`:''}${conditionHtml(item)}</div></li>`;
  }
  if(item.type==='destination'){
    const acts=(item.activities||[]).map(x=>x.label||x.activity).filter(Boolean).join(' / ');const stay=item.stay_duration||item.duration_estimate;
    return `<li class="flow-item destination"><div class="flow-icon">●</div><div><div class="flow-title">${endpoint(item.destination_ref)} ${item.role?badge(roleLabel(item.role)):''}</div>${stay?`<div class="flow-detail">滞在 ${esc(stay)}</div>`:''}${acts?`<div class="flow-note">${esc(acts)}</div>`:''}${conditionHtml(item)}</div></li>`;
  }
  if(item.type==='route'){
    return `<li class="flow-item route"><div class="flow-icon">★</div><div><div class="flow-title">${refInline(item.route_ref||{})}</div>${routeStops(item.ordered_spot_refs||[])}${(item.adjustments||[]).map(x=>`<div class="flow-note">${esc(x)}</div>`).join('')}${conditionHtml(item)}</div></li>`;
  }
  if(item.type==='free_time')return `<li class="flow-item free-time"><div class="flow-icon">○</div><div><div class="flow-title">${esc(item.label||'自由時間')}</div>${(item.notes||[]).map(x=>`<div class="flow-note">${esc(x)}</div>`).join('')}</div></li>`;
  return'';
}
function conditionHtml(item){const groups=[item.conditions,item.time_constraints,item.feasibility].filter(x=>x&&typeof x==='object');const pairs=groups.flatMap(g=>Object.entries(g).filter(([,v])=>v!==null&&v!==undefined&&v!==''&&typeof v!=='object'));return pairs.length?`<div class="exec-conditions">${pairs.map(([k,v])=>`<span>${esc(String(v))}</span>`).join('')}</div>`:'';}
function timeBudget(tb={}){const chips=[tb.expected_total,tb.preferred_start].filter(Boolean).map(badge).join('');const constraints=(tb.constraints||[]).map(x=>`<span>${esc(x)}</span>`).join('');return chips||constraints?`<div class="day-time">${chips}${constraints?`<div class="day-constraints">${constraints}</div>`:''}</div>`:'';}
function dayPlan(day){return `<article class="day-card"><details><summary><div class="day-number">${esc(day.day)}日目</div><div><h3>${esc(day.purpose||'')}</h3><p>${esc(day.summary||'')}</p></div></summary><div class="day-card-body">${timeBudget(day.time_budget||{})}${day.start||day.end?`<div class="day-endpoints">${endpoint(day.start)}<span>→</span>${endpoint(day.end)}</div>`:''}<div class="plan-day-subhead">1日のFlow</div><ol class="flow-list">${(day.flow||[]).map(x=>flowItem(x)).join('')}</ol></div></details></article>`;}
function tripValue(v={}){const cards=(v.highlights||[]).map(x=>`<article class="card value-card">${esc(x)}</article>`).join('');const rows=[['旅の流れ',v.flow],['体験の幅',v.diversity],['移動効率',v.travel_efficiency],['トレードオフ',Array.isArray(v.tradeoffs)?v.tradeoffs.join(' / '):v.tradeoffs]].filter(([,x])=>x);return `<details class="section collapsible"><summary>この旅の価値</summary><div class="collapsible-body">${v.summary?`<p>${esc(v.summary)}</p>`:''}${cards?`<div class="cards">${cards}</div>`:''}${rows.length?`<dl class="fact-grid">${rows.map(([k,x])=>`<div><dt>${esc(k)}</dt><dd>${esc(x)}</dd></div>`).join('')}</dl>`:''}</div></details>`;}
function estimatedCost(v={}){const breakdown=v.breakdown||[];if(!v.total&&!breakdown.length)return'';return `<details class="section collapsible"><summary>費用の内訳</summary><div class="collapsible-body">${v.total?`<p><strong>${esc(v.total)}</strong></p>`:''}${breakdown.length?`<ul class="list">${breakdown.map(x=>`<li>${esc(typeof x==='string'?x:(x.label||JSON.stringify(x)))}</li>`).join('')}</ul>`:''}</div></details>`;}
function renderPlan(data){const p=data.plan||{};breadcrumb.innerHTML=`<a href="./">Home</a><span>›</span><span>${esc(data.id)}</span>`;const cpRefs=data.concrete_plan_refs||[];app.innerHTML=`<section class="hero"><div class="kicker">旅のプラン · ${esc(data.id)}</div><h1>${esc(data.title)}</h1><p class="summary">${esc(data.summary||'')}</p>${p.transport?.primary?`<div class="hero-meta">${badge(modeLabel(p.transport.primary))}</div>`:''}</section>${cpRefs.length?`<div class="mode-switch"><span class="badge">計画</span>${cpRefs.map(x=>`<a href="${hrefFor(x)}">実施</a>`).join('')}</div>`:''}${tripValue(p.trip_value||{})}${(data.hero_refs||[]).length?`<section class="section"><h2>この旅の主役</h2><div class="cards">${data.hero_refs.map(refCard).join('')}</div></section>`:''}<section class="section itinerary"><h2>日ごとの旅程</h2>${(p.days||[]).map(dayPlan).join('')}</section>${estimatedCost(p.estimated_cost||{})}`;}
function renderRoute(data){const r=data.route||{},m=data.map||null;breadcrumb.innerHTML=`<a href="./">Home</a><span>›</span>${(data.parent_refs||[]).map(x=>`${refInline(x)}<span>›</span>`).join('')}<span>${esc(data.id)}</span>`;const facts=[['所要時間',r.duration],['難易度',difficultyLabel(r.difficulty)],['移動',r.route_type==='driving'?'車':r.route_type]].filter(([,v])=>v);app.innerHTML=`<section class="hero"><div class="kicker">ルート · ${esc(data.id)}</div><h1>${esc(data.title)}</h1><p class="summary">${esc(data.summary||'')}</p><p>${esc(r.purpose||'')}</p>${facts.length?`<dl class="fact-grid">${facts.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`:''}</section>${(r.highlights||[]).length?`<details class="section collapsible"><summary>このルートの魅力</summary><div class="collapsible-body"><p>${esc(r.appeal?.summary||'')}</p><div class="cards">${r.highlights.map(x=>`<article class="card">${esc(x)}</article>`).join('')}</div></div></details>`:''}${m?`<section class="section"><h2>ルートの地図</h2><div class="map-wrap"><div id="route-map" class="exec-map"></div><div id="route-map-message" class="map-message"></div></div><p class="note">立ち寄り順を示す概念地図です。</p></section>`:''}<section class="section"><h2>立ち寄り順</h2><div class="route-stops vertical">${(r.sequence||[]).map((x,i)=>`<span class="route-stop"><span class="stop-no">${i+1}</span>${refInline(x)}${x.role?` <small>${esc(roleLabel(x.role))}</small>`:''}</span>`).join('')}</div></section>${(r.constraints||[]).length?`<section class="section"><h2>重要な条件</h2><ul class="list">${r.constraints.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}`;if(m)renderGoogleMap('route-map','route-map-message',m,r.sequence||[]);}
function imageGallery(raw=[]){const urls=raw.map(x=>typeof x==='string'?x:(x.url||x.source_url||x.image_url||'')).filter(Boolean);return urls.length?`<section class="section"><h2>写真</h2><div class="image-grid">${urls.map((u,i)=>`<figure class="image-card"><img src="${esc(u)}" loading="lazy" alt="写真 ${i+1}" onerror="this.closest('figure').remove()"></figure>`).join('')}</div></section>`:'';}
function renderSpot(data){const s=data.spot||{};breadcrumb.innerHTML=`<a href="./">Home</a><span>›</span><span>${esc(data.id)}</span>`;app.innerHTML=`<section class="hero"><div class="kicker">スポット · ${esc(data.id)}</div><h1>${esc(data.title)}</h1><p class="summary">${esc(data.summary||'')}</p></section>${imageGallery(s.image_refs||[])}${(s.highlights||[]).length?`<section class="section"><h2>魅力</h2><div class="cards">${s.highlights.map(x=>`<article class="card">${esc(x)}</article>`).join('')}</div></section>`:''}${(s.value_points||[]).length?`<section class="section"><h2>このスポットの価値</h2><ul class="list">${s.value_points.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}${(s.practicality||[]).length?`<section class="section"><h2>利用情報</h2><ul class="list">${s.practicality.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}`;}
function statusClass(v=''){return ['viable','ready','confirmed'].includes(v)?'status-good':['conditional'].includes(v)?'status-warn':['cancelled','infeasible'].includes(v)?'status-bad':'status-unknown';}
function objectSummary(obj={}){return Object.entries(obj||{}).filter(([,v])=>v!==null&&v!==undefined&&v!==''&&typeof v!=='object').map(([k,v])=>[k,v]);}
function feasibilityBox(v={}){const rows=objectSummary(v);return rows.length?`<div class="weather-box"><strong class="${statusClass(v.status||v.feasibility)}">${esc(statusLabel(v.status||v.feasibility||'判断'))}</strong><div class="exec-conditions">${rows.map(([,x])=>`<span>${esc(x)}</span>`).join('')}</div></div>`:'';}
function weatherBox(v){if(!v)return'';const rows=objectSummary(v);return `<div class="weather-box"><strong>天候判断</strong>${rows.length?`<div class="exec-conditions">${rows.map(([,x])=>`<span>${esc(x)}</span>`).join('')}</div>`:''}</div>`;}
function summaryGrid(v={}){const rows=Object.entries(v||{}).filter(([,x])=>x!==null&&x!==undefined&&x!==''&&typeof x!=='object');return rows.length?`<div class="exec-summary-grid">${rows.map(([k,x])=>`<div><span>${esc(k.replaceAll('_',' '))}</span><strong>${esc(x)}</strong></div>`).join('')}</div>`:'';}
function alternativeHtml(items=[]){if(!items.length)return'';return `<div class="decision-grid">${items.map(x=>`<article class="decision-card"><strong>${refInline(x.route_ref||x.target_route_ref||{})||esc(x.label||'代替案')}</strong>${(x.switch_conditions||[]).length?`<ul class="switch-conditions">${x.switch_conditions.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>`:''}</article>`).join('')}</div>`;}
function concreteDay(day,cpId){const variants=day.variants||[];return `<article class="day-card exec-day" data-day="${esc(day.day)}"><details><summary><div class="day-number">Day ${esc(day.day)}</div><div><h3>${day.date?`${esc(day.date)} · `:''}${esc(day.purpose||'')}</h3><p>${esc(day.summary||'')}</p></div></summary><div class="day-card-body"><div class="day-overview"><h4>1日の概要</h4>${timeBudget(day.time_budget||{})}<p>${esc(day.summary||'')}</p></div>${alternativeHtml(day.alternatives||[])}${feasibilityBox(day.feasibility||{})}${weatherBox(day.weather_assessment)}${variants.length>1?`<div class="variant-tabs">${variants.map((v,i)=>`<button data-variant="${esc(v.variant_id)}" class="${i===0?'active':''}">${esc(v.label||v.variant_id)}</button>`).join('')}</div>`:''}<div class="variant-host">${variants.length?variantPanel(variants[0],day.day,cpId):'<p class="empty">実施variantがありません。</p>'}</div></div></details></article>`;}
function variantPanel(v,dayNo,cpId){const mapId=`exec-map-${cpId}-${dayNo}-${v.variant_id}`.replace(/[^A-Za-z0-9_-]/g,'-');return `<div class="variant-panel" data-active-variant="${esc(v.variant_id)}">${summaryGrid(v.summary||{})}<div class="view-tabs"><button class="active" data-view="flow">行動順</button><button data-view="map">マップ</button></div><div class="view-panel" data-panel="flow"><ol class="flow-list">${(v.flow||[]).map(x=>flowItem(x,true)).join('')}</ol></div><div class="view-panel" data-panel="map" hidden><div class="exec-map-wrap"><div id="${mapId}" class="exec-map"></div><div id="${mapId}-message" class="exec-map-message"></div></div></div></div>`;}
function bindConcrete(data){const cp=data.concrete_plan||{};app.querySelectorAll('.exec-day').forEach(card=>{const dayNo=Number(card.dataset.day);const day=(cp.days||[]).find(x=>Number(x.day)===dayNo);if(!day)return;const host=card.querySelector('.variant-host');card.querySelectorAll('.variant-tabs button').forEach(btn=>btn.addEventListener('click',()=>{card.querySelectorAll('.variant-tabs button').forEach(x=>x.classList.toggle('active',x===btn));const v=(day.variants||[]).find(x=>x.variant_id===btn.dataset.variant);if(v){host.innerHTML=variantPanel(v,dayNo,data.id);bindVariantViews(host,v,dayNo,data.id);}}));const first=(day.variants||[])[0];if(first)bindVariantViews(host,first,dayNo,data.id);});}
function bindVariantViews(host,variant,dayNo,cpId){host.querySelectorAll('.view-tabs button').forEach(btn=>btn.addEventListener('click',()=>{host.querySelectorAll('.view-tabs button').forEach(x=>x.classList.toggle('active',x===btn));host.querySelectorAll('.view-panel').forEach(p=>p.hidden=p.dataset.panel!==btn.dataset.view);if(btn.dataset.view==='map'){const mapId=`exec-map-${cpId}-${dayNo}-${variant.variant_id}`.replace(/[^A-Za-z0-9_-]/g,'-');renderGoogleMap(mapId,`${mapId}-message`,variant.map||{},[]);}}));}
function fuelHtml(fuel){if(!fuel)return'';const stations=(fuel.station_refs||[]).map(x=>refInline(x.ref||{})).filter(Boolean);return `<details class="section collapsible"><summary>給油計画</summary><div class="collapsible-body"><div class="fuel-box">${stations.length?`<p>候補: ${stations.join(' / ')}</p>`:''}${summaryGrid(fuel.estimate||{})}</div></div></details>`;}
function costHtml(cost){if(!cost||!Object.keys(cost).length)return'';return `<details class="section collapsible"><summary>旅全体の費用</summary><div class="collapsible-body"><div class="cost-box">${summaryGrid(cost)}</div></div></details>`;}
function renderConcrete(data){const cp=data.concrete_plan||{},source=cp.source_plan_ref||{};breadcrumb.innerHTML=`<a href="./">Home</a><span>›</span>${refInline(source)}<span>›</span><span>${esc(data.id)}</span>`;const win=cp.execution_window||{};app.innerHTML=`<section class="hero"><div class="kicker">実施プラン · ${esc(data.id)}</div><h1>${esc(data.title)}</h1><p class="summary">${esc(data.summary||'')}</p><div class="exec-meta">${badge(statusLabel(cp.status))}${win.start_date&&win.end_date?badge(`${win.start_date}〜${win.end_date}`):''}${(cp.primary_transport||[]).map(x=>badge(modeLabel(x))).join('')}${cp.last_verified_at?badge(`確認 ${cp.last_verified_at}`):''}</div></section>${source.id?`<div class="mode-switch"><a href="${hrefFor(source)}">計画</a><span class="badge">実施</span></div>`:''}<section class="section"><h2>日ごとの実施計画</h2>${(cp.days||[]).map(d=>concreteDay(d,data.id)).join('')}</section>${fuelHtml(cp.fuel_plan)}${costHtml(cp.cost_summary)}`;bindConcrete(data);}
function googleSearch(name,placeId=''){const p=new URLSearchParams({api:'1',query:name});if(placeId)p.set('query_place_id',placeId);return `https://www.google.com/maps/search/?${p}`;}
function popup(point){const ref={type:point.entity_type,id:point.entity_id};return `<div class="pin-popup"><strong>${esc(point.name||point.entity_id)}</strong>${point.role?`<div>${esc(roleLabel(point.role))}</div>`:''}<div class="pin-links">${canOpen(ref)?`<a href="${hrefFor(ref)}">PersonalOSで見る</a>`:''}<a href="${esc(googleSearch(point.name||point.entity_id,point.place_id||''))}" target="_blank" rel="noopener">Google Mapsで開く</a></div></div>`;}
function decodePolyline(encoded){const path=[];let index=0,lat=0,lng=0;while(index<encoded.length){let result=0,shift=0,byte;do{byte=encoded.charCodeAt(index++)-63;result|=(byte&0x1f)<<shift;shift+=5;}while(byte>=0x20);lat+=(result&1)?~(result>>1):(result>>1);result=0;shift=0;do{byte=encoded.charCodeAt(index++)-63;result|=(byte&0x1f)<<shift;shift+=5;}while(byte>=0x20);lng+=(result&1)?~(result>>1):(result>>1);path.push({lat:lat/1e5,lng:lng/1e5});}return path;}
let googlePromise;function ensureGoogleMaps(key){if(window.google?.maps)return Promise.resolve();if(googlePromise)return googlePromise;googlePromise=new Promise((resolve,reject)=>{window.__personalosGoogleMapsReady=resolve;const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&callback=__personalosGoogleMapsReady&v=weekly`;s.async=true;s.defer=true;s.onerror=()=>reject(new Error('Google Maps JavaScript API load error'));document.head.appendChild(s);});return googlePromise;}
async function renderGoogleMap(mapId,messageId,spec,sequence=[]){const el=document.getElementById(mapId),message=document.getElementById(messageId);if(!el||!message||el.dataset.loaded)return;const key=window.PERSONALOS_CONFIG?.googleMapsApiKey||'';if(!key){message.textContent='Google Maps API key 未設定。';return;}try{await ensureGoogleMaps(key);const points=await fetchJson(spec.points_json);const map=new google.maps.Map(el,{mapTypeControl:true,streetViewControl:false,fullscreenControl:true});const info=new google.maps.InfoWindow(),bounds=new google.maps.LatLngBounds();(points.points||[]).forEach(point=>{const pos={lat:Number(point.lat),lng:Number(point.lon)};bounds.extend(pos);const marker=new google.maps.Marker({map,position:pos,label:point.order?{text:String(point.order),color:'#fff',fontWeight:'700'}:undefined,title:point.name||point.entity_id});marker.addListener('click',()=>{info.setContent(popup(point));info.open({map,anchor:marker});});});for(const routeRef of spec.execution_routes||[]){try{const artifact=await fetchJson(routeRef.path);const encoded=(artifact.encoded_polyline_chunks||[]).join('');if(encoded){const path=decodePolyline(encoded);path.forEach(p=>bounds.extend(p));new google.maps.Polyline({map,path,strokeWeight:5});}}catch(e){message.textContent=`一部の実道路線を読み込めませんでした: ${e.message}`;}}if(!bounds.isEmpty())map.fitBounds(bounds,28);el.dataset.loaded='1';if(!message.textContent)message.textContent='';}catch(e){message.textContent=`地図の読み込みに失敗しました: ${e.message}`;}}
function renderHome(manifest){document.title='PersonalOS Leisure';breadcrumb.innerHTML='';const items=manifest.items||[];const section=(title,t)=>{const rows=items.filter(x=>x.type===t);return rows.length?`<section class="section"><h2>${esc(title)}</h2><div class="home-list">${rows.map(x=>`<div class="home-item"><a href="${hrefFor(x)}"><strong>${esc(x.title||x.id)}</strong></a><span class="badge">${esc(x.id)}</span></div>`).join('')}</div></section>`:'';};app.innerHTML=`<section class="hero"><div class="kicker">PersonalOS Leisure</div><h1>レジャー</h1><p class="summary">旅の計画から実施、ルート、スポットへ掘り下げて見られます。</p></section>${section('旅のプラン','plan')}${section('実施プラン','concrete_plan')}${section('ルート','route')}${section('スポット','spot')}`;}
async function main(){try{const manifest=await fetchJson('./manifest.json');published=new Set((manifest.items||[]).map(keyFor));if(!type||!id){renderHome(manifest);return;}if(!dirs[type])throw new Error(`unsupported type: ${type}`);if(!published.has(`${type}:${id}`))throw new Error(`not published: ${type}:${id}`);const data=await fetchJson(pathFor(type,id));document.title=`${data.title} · PersonalOS Leisure`;if(type==='plan')renderPlan(data);else if(type==='concrete_plan')renderConcrete(data);else if(type==='route')renderRoute(data);else if(type==='spot')renderSpot(data);}catch(e){app.innerHTML=`<section class="section"><h1>表示できませんでした</h1><p class="error">${esc(e.message)}</p><p><a href="./">Homeへ戻る</a></p></section>`;}}
main();
